### ISSUE TITLE
Death during aftershow 72

### ISSUE THREAD

**Issue by jeremybanks** [cliss/accidentalbot#29]
from https://gist.github.com/cliss/c618e3e20f9539f69568:

```
2014-07-01T02:42:51.132915+00:00 app[web.1]: /app/node_modules/ws/lib/WebSocket.js:187
2014-07-01T02:42:51.132453+00:00 app[web.1]: 
2014-07-01T02:42:51.133218+00:00 app[web.1]:     else throw new Error('not opened');
2014-07-01T02:42:51.133233+00:00 app[web.1]:                ^
2014-07-01T02:42:51.135282+00:00 app[web.1]: Error: not opened
2014-07-01T02:42:51.135285+00:00 app[web.1]:     at WebSocket.send (/app/node_modules/ws/lib/WebSocket.js:187:16)
2014-07-01T02:42:51.135287+00:00 app[web.1]:     at /app/accidentalbot.js:17:20
2014-07-01T02:42:51.135288+00:00 app[web.1]:     at Array.forEach (native)
2014-07-01T02:42:51.135290+00:00 app[web.1]:     at sendToAll (/app/accidentalbot.js:16:17)
2014-07-01T02:42:51.135292+00:00 app[web.1]:     at WebSocket.<anonymous> (/app/accidentalbot.js:266:21)
2014-07-01T02:42:51.135293+00:00 app[web.1]:     at WebSocket.emit (events.js:98:17)
2014-07-01T02:42:51.135295+00:00 app[web.1]:     at Receiver.self._receiver.ontext (/app/node_modules/ws/lib/WebSocket.js:697:10)
2014-07-01T02:42:51.135297+00:00 app[web.1]:     at Receiver.opcodes.1.finish (/app/node_modules/ws/lib/Receiver.js:397:14)
2014-07-01T02:42:51.135298+00:00 app[web.1]:     at Receiver.expectHandler (/app/node_modules/ws/lib/Receiver.js:378:33)
2014-07-01T02:42:51.135300+00:00 app[web.1]:     at Receiver.add (/app/node_modules/ws/lib/Receiver.js:93:24)
```

I previously had a local test that repeatedly opened connections, sent a ton of messages, and then immediately closed the connection, to try to see if there was any race condition. I never triggered a crash with that, but I don't think I used very many concurrent connections, as would happen during the real show.

If someone can reproduce this behaviour reliably so we can put it in a test, that would be fantastic.

**Comment by cliss** [comment]
Assuming fixed.
